import numpy as np
import traitlets
from astropy import units as u

from .. import rng
from ..noise_sim import AnalyticNoise
from ..timing import function_timer
from ..traits import Bool, Float, Int, Unicode
from ..utils import Logger
from .operator import Operator


class VariableNoiseModel(Operator):
    """Create a noise model that varies across the focal plane.

    The nominal noise model has 4 parameters per detector: fknee, alpha, NET, fmin.
    A variable noise model is generated by varying the first three parameters around their
    nominal values. The ``scatter`` trait controls this relative variation (set it to zero
    to disable).

    To generate a white noise model, use the ``white`` trait. Internally this will set all
    parameters to zero except the NET.

    To create a model without mismatch between A and B detectors, but only between pairs of
    detectors, use the ``pairs`` trait, which will apply the same variation to both detectors.

    On the contrary, to simulate a systematic mismatch between A and B detectors, use the
    ``biased`` trait, which will apply the opposite variation to B detectors.
    """

    # Class traits
    API = Int(0, help='Internal interface version for this operator')
    biased = Bool(False, help='Introduce a systematic mismatch between A and B detectors')
    noise_model = Unicode('var_noise_model', help='The observation key for storing the noise model')
    pairs = Bool(False, help='Process detectors by pairs instead of individually')
    realization = Int(0, help='The model realization index')
    scatter = Float(0.1, help='Fractional scatter in the noise parameters')
    white = Bool(False, help='Generate a white noise model')

    @traitlets.validate('realization')
    def _check_realization(self, proposal):
        check = proposal['value']
        if check < 0:
            raise traitlets.TraitError('realization index must be positive')
        return check

    @traitlets.validate('biased')
    def _check_biased(self, proposal):
        check = proposal['value']
        if check and self.pairs:
            raise traitlets.TraitError('Cannot use both pairs and biased')
        return check

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    @function_timer
    def _exec(self, data, detectors=None, **kwargs):
        log = Logger.get()

        noise_keys = set(['psd_fmin', 'psd_fknee', 'psd_alpha', 'psd_net'])

        for ob in data.obs:
            sindx = ob.session.uid
            telescope = ob.telescope.uid
            fp_data = ob.telescope.focalplane.detector_data
            has_parameters = False
            for key in noise_keys:
                if key not in fp_data.colnames:
                    break
            else:
                has_parameters = True
            if not has_parameters:
                msg = f'Observation {ob.name} does not have a focalplane with '
                msg += 'noise parameters.  Skipping.'
                log.warning(msg)
                ob[self.noise_model] = None
                continue

            local_dets = set(ob.local_detectors)

            dets = []
            fmin = {}
            fknee = {}
            alpha = {}
            NET = {}
            rates = {}
            indices = {}

            key1 = (
                int(self.realization) * int(4294967296) + int(telescope) * int(65536) + int(sindx)
            )

            def _process(row, row_b=None):
                # Check if the detector is local to this process
                if row['name'] not in local_dets:
                    return

                # Draw three random values
                # Using only the uid of the first row
                detindx = row['uid']
                rngdata = np.array(rng.random(3, sampler='gaussian', key=(key1, detindx)))

                # Populate the noise model
                names = [row['name']] if row_b is None else [row['name'], row_b['name']]
                if self.pairs:
                    coeff_b = rngdata
                elif self.biased:
                    coeff_b = -rngdata
                coeffs = [rngdata] if row_b is None else [rngdata, coeff_b]
                detindxs = [detindx] if row_b is None else [detindx, row_b['uid']]
                for name, coeff, indx in zip(names, coeffs, detindxs):
                    dets.append(name)
                    rates[name] = ob.telescope.focalplane.sample_rate
                    fmin[name] = row['psd_fmin']
                    if self.white:
                        fknee[name] = u.Quantity(0.0, u.Hz)
                        alpha[name] = 0.0
                    else:
                        fknee[name] = row['psd_fknee'] * (1 + self.scatter * coeff[0])
                        alpha[name] = row['psd_alpha'] * (1 + self.scatter * coeff[1])
                    NET[name] = row['psd_net'] * (1 + self.scatter * coeff[2])
                    indices[name] = indx

            if self.pairs or self.biased:
                # iterate over pairs of detectors
                for row_a, row_b in pairwise(fp_data):
                    _process(row_a, row_b)
            else:
                # iterate over single detectors
                for row in fp_data:
                    _process(row)

            ob[self.noise_model] = AnalyticNoise(
                rate=rates,
                fmin=fmin,
                detectors=dets,
                fknee=fknee,
                alpha=alpha,
                NET=NET,
                indices=indices,
            )

    def _finalize(self, data, **kwargs):
        return

    def _requires(self):
        return dict()

    def _provides(self):
        prov = {'meta': [self.noise_model]}
        return prov


def pairwise(iterable):
    """Iterate over pairs of elements in an iterable."""
    a = iter(iterable)
    return zip(a, a, strict=True)
